defaultProject: lithe-vent-382809       # es. bofrost-data-import
defaultLocation: europe-west3

defaultDataset: moca_metrics
defaultAssertionDataset: moca_metrics_assertions

vars:
  client_name: smegit              # es. bofrost
  source_project: lithe-vent-382809     # es. bofrost-data-import

  source_dataset: moca_metrics
  source_table: cookieless_raw_data

  client_domain: smeg.com          # es. bofrost.it

  # Timezone del cliente per il calcolo delle date e delle sessioni
  timezone: Europe/Rome

  # Timeout sessione in secondi (default 30 minuti)
  session_timeout: "1800"
